config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#index'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :users
  resources :books, only: [:new, :create, :index, :show, :destroy, :update, :edit] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  
  has_many :book_comments, dependent: :destroy
  
  validates :title, presence: true
  validates :body,presence: true, length: { maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  attachment :profile_image

  has_many :favorites, dependent: :destroy

  def already_favorited?(book)
    self.favorites.exists?(book_id: book.id)
  end

  has_many :book_comments,dependent: :destroy


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:index, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
    devise_parameter_sanitizer.permit(:sign_in,keys:[:name])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @book = Book.find(params[:book_id])
    @comment = @book.book_comments.find(params[:id])
    @comment.destroy
    redirect_to book_path(params[:book_id])
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment, :book_id)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @commentuser = current_user
  end

  def new
    @book = Book.new
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id =current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      render :index
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @favorite = current_user.favorites.create(book_id: params[:book_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @book = Book.new
    @users = User.all
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_error.html.erb
<% if book.errors.any? %>
  <%= book.errors.count %>errors prohibited this obj from being saved:
  <% book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

app/views/books/_index.html.erb
        <table>
          <tr>
            <th></th>
            <th>Title</th>
            <th>opinion</th>
            <th></th>
            <th></th>
          </tr>
          <% books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag(book.user, :profile_image, :fill, 40, 40, fallback: "no-image-icon.jpg") %>
              <% end %>
            </td>
            <td><%= link_to book_path(book.id) do %><%= book.title %><% end %></td>
            <td><%= book.body %></td>
            <td>
              <% if current_user.already_favorited?(book) %>
                <%= link_to book_favorites_path(book), method: :delete do %>
                  <i class="fas fa-heart"></i>
                  <%= book.favorites.count %>
                <% end %>
              <% else %>
                <%= link_to book_favorites_path(book), method: :post do %>
                  <i class="far fa-heart"></i>
                  <%= book.favorites.count %>
                <% end %>
              <% end %>
            </td>
            <td>
              コメント件数：<%= book.book_comments.count %>
            </td>
          </tr>
          <% end %>
        </table>

app/views/books/_post.html.erb
   <%= form_with model:book, local:true do |f| %>
  Title<br>
    <%= f.text_field :title %><br>
  Opinion<br>
    <%= f.text_area :body %><br>
    <% if f.object.new_record? %>
      <%= f.submit "Create Book" %>
    <% else %>
      <%= f.submit "Update Book" %>
    <% end %>
  <% end %>

app/views/books/edit.html.erb
<div class="container">
  <%= render 'books/error',book: @book %>
  <div class="row">
    <div class="mx-auto  col-sm-10 col-xl-6">
      <h1>Editing Book</h1>
        <%= render 'books/post', book: @book %>
        <%= link_to "Show", book_path(@book) %> |
        <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<%= render 'books/error',book: @book %>

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info', user: current_user %>
    <h2>New book</h2>
      <%= render 'books/post', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
        <%= render 'books/index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info', user: @book.user %>
      <h2>New book</h2>
      <%= render 'books/post', book: Book.new %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
        <table>
          <tr>
            <td>
              <%= link_to user_path(@book.user) do %>
                <%= attachment_image_tag(@book.user, :profile_image, :fill, 40, 40, fallback: "no-image-icon.jpg") %><br>
                <%= @book.user.name %>
              <% end %>
            <td>
            <%= link_to book_path(@book) do %>
              <%= @book.title %>
            <% end %>
            </td>
            <td><%= @book.body %></td>
            <% if @book.user == current_user %>
            <td>
              <%= link_to edit_book_path(@book) do %>Edit
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book), method: :delete do %>
              Destroy</td>
              <% end %>
            <% else %>
            <td>
              <% if current_user.already_favorited?(@book) %>
                <%= link_to book_favorites_path(@book), method: :delete do %>
                  <i class="fas fa-heart"></i>
                  <%= @book.favorites.count %>
                <% end %>
              <% else %>
                <%= link_to book_favorites_path(@book), method: :post do %>
                  <i class="far fa-heart"></i>
                  <%= @book.favorites.count %>
                <% end %>
              <% end %>
            </td>
            <% end %>
            <td>
              コメント件数：<%= @book.book_comments.count %>
            </td>

          </tr>
        </table>

        <% @book.book_comments.each do |book_comment| %>
        <div>
          <%= image_tag('no-image-icon.jpg') %>
          <%= book_comment.user.name %>
          <% if book_comment.user == current_user %>
          <%= book_comment.comment %>
            <%= link_to book_book_comment_path(book_comment.book, book_comment), method: :delete,data: {confirm: "Are you sure?"} do %>
              <button type="button" class="btn btn-danger">Destroy</button>
            <% end %>
          <% end %>
        </div>
        <% end %>

        <div>
          <%= form_with(model:[@book, @book_comment], local:true) do |f| %>
            <%= f.text_area :comment, rows:'5',cols:"70" %><br>
            <%= f.submit "送信" %>
          <% end %>
        </div>


    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto  col-sm-10 col-xl-6">
      <h1>Welcome to <strong><i class="fas fa-book"></i>Bookers</strong>!!</h1>
    </div>
  </div>
</div>

app/views/homes/index.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto  col-sm-10 col-xl-6">
      <h1>Welcome to <strong><i class="fas fa-book"></i>Bookers</strong>!!</h1>
      <p>In <i class="fas fa-book"></i>Bookers,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      
        <div class="button">
          <%= link_to"Log in",new_user_session_path, class: "btn btn-info btn-primary btn-block" %><br>
          <%= link_to"Sign up",new_user_registration_path, class: "btn btn-success btn-block"  %>
        </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

   <!-- FontAwesomeの読み込み -->
      <!-- FontAwesomeの読み込み -->
    <script src="https://kit.fontawesome.com/a089111b95.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <%= link_to user_path(current_user) do %>
                  <li class="nav-item">
                    <i class="fas fa-home" style="color:white"></i>Home
                  </li>
                <% end %>
                <%= link_to users_path do %>
                  <li class="nav-item">
                    <i class="fas fa-users" style="color:white"></i>Users
                  </li>
                <% end %>
                <%= link_to books_path do %>
                  <li class="nav-item">
                    <i class="fas fa-book-open" style="color:white"></i>Books
                  </li>
                <% end %>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <li class="nav-item">
                    <i class="fas fa-sign-out-alt" style="color:white"></i>Log out
                  </li>
                <% end %>
              <% else %>
                <%= link_to root_path do %>
                  <li class="nav-item">
                    <i class="fas fa-home" style="color:white"></i>Home
                  </li>
                <% end %>
                <%= link_to home_about_path do %>
                  <li class="nav-item">
                    <i class="fas fa-link" style="color:white"></i>About
                  </li>
                <% end %>
                <%= link_to new_user_registration_path do %>
                  <li class="nav-item">
                    <i class="fas fa-user-plus" style="color:white"></i>Sign up
                  </li>
                <% end %>
                <%= link_to new_user_session_path do %>
                  <li class="nav-item">
                    <i class="fas fa-sign-in-alt" style="color:white"></i>Log in
                  </li>
                <% end %>
            </ul>
              <% end %>
          </div>
        </div>
      </nav>
      </header>

      <main>

        <%= notice %>
        <%= yield %>
      </main>

      <footer>CopyRight Infratop.inc</footer>
  </body>
</html>

app/views/users/_info.html.erb
<h2>User info</h2>
<%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %>
<table>
  <tr>
    <td><strong>name</strong></td><td><%= user.name %></td>
  </tr>
  <tr>
    <td><strong>introduction</strong></td><td><%= user.introduction %></td>
  </tr>
</table>
<%= link_to edit_user_path(user) do %>
<button type="button" class="btn btn-outline-secondary btn-block"><i class="fas fa-user-cog"></i></button>
<% end %>

app/views/users/edit.html.erb
<%= render 'books/error',book: @user %>

<div class="container">
  <div class="row">
    <div class="mx-auto  col-sm-10 col-xl-6">
      <h1>User info</h1>
        <%= form_with model:@user, local:true do |f| %>
        <h4>name</h4>
          <%= f.text_field :name %>
        <h4>Image</h4>
          <%= f.attachment_field :profile_image %>
        <h4>introduction</h4>
          <%= f.text_area :introduction %><br>
          <%= f.submit 'Update User' %>
        <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'books/error',book: @book %>

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info',user: current_user %>
      <h2>New book</h2>
      <%= render 'books/post',book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
        <table>
          <tr>
            <th>images</th>
            <th>name</th>
            <th></th>
          </tr>
          <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag(user, :profile_image, :fill, 40, 40, fallback: "no-image-icon.jpg") %></td>
            <td><%= user.name %></td>
            <td>
              <%=link_to "Show",user_path(user.id) %></td>
          <% end %>
          </tr>
        </table>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info',user: @user %>
      <h2>New book</h2>
      <%= render 'books/post',book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
        <%= render 'books/index', books: @books %>
    </div>
  </div>
</div>